# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'E-Plant' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for E-Plant
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'

  target 'E-PlantTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'E-PlantUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
